name: flutter_application_1

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.4.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^10.1.2
  shared_preferences: ^2.2.1
  convert: ^3.1.1
  flutter_lints: ^3.0.2
  test: any
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  nock: ^1.2.3
  flutter_lints: ^3.0.0

# and if necessary

environment:
  sdk: '^3.4.0'
